spring.application.name=QHSEAnalytics


## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/qhse_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
# Validate existing schema; switch to update for local development if tables are missing
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true



# MySQL (XAMPP)
#spring.datasource.url=jdbc:mysql://localhost:3306/qhse_db?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.defer-datasource-initialization=true


# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=analyticsqhse@gmail.com
spring.mail.password=aobg noqk ovmw mwar
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.from=analyticsqhse@gmail.com

# JWT
app.jwt.secret=cce6d6a7c9b79a8e674077ad15841013750793bd0c80d5936a57754872bf29d1
app.jwt.access-token-expiration=1800000
app.jwt.refresh-token-expiration=3600000
app.jwt.refresh-token-remember-expiration=604800000

# OTP
app.otp.expiration-minutes=10

# Verification email
app.email-token.expiration-hours=24
app.email-token.resend-cooldown-minutes=2

# Reset password
app.password-reset.expiration-hours=1

# Admin par default
app.admin.email=analyticsqhse@gmail.com
app.admin.password=Admin2004@
app.admin.nom=Super
app.admin.prenom=Admin

# URL Frontend
app.frontend.url=http://localhost:4200

# CORS
app.cors.allowed-origins=http://localhost:4200

# Groq
app.groq.api-keys=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,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,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
app.groq.models=llama-3.3-70b-versatile,meta-llama/llama-4-scout-17b-16e-instruct,qwen/qwen3-32b
app.groq.timeout=30

# Gemini
app.gemini.api-key=AIzaSyDTqN9AuFzwVrBEsIzp0fUtKXsbCjfhGEA
app.gemini.model=gemini-2.0-flash
app.gemini.url=https://generativelanguage.googleapis.com/v1beta/models/

# Import automatique KPI
app.import.matching.fuzzy-threshold=0.85
app.import.matching.review-threshold=0.85
app.import.validator.taux-max=100.0

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.server.port=8080