spring.application.name=QHSEAnalytics

server.port=8080

# MySQL (XAMPP)
spring.datasource.url=jdbc:mysql://localhost:3306/qhse_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=analyticsqhse@gmail.com
spring.mail.password=aobg noqk ovmw mwar
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.from=

# JWT

app.jwt.secret=c4f3a9e8b7d6c1f2e3a4b5c6d7e8f90123456789abcdef0123456789abcdef0

# 30 min
app.jwt.access-token-expiration=1800000

# 1h
app.jwt.refresh-token-expiration=3600000

# 7 jours
app.jwt.refresh-token-remember-expiration=604800000


# OTP
app.otp.expiration-minutes=10

# Verification email
app.email-token.expiration-hours=24
app.email-token.resend-cooldown-minutes=2

# Reset password
app.password-reset.expiration-hours=1

# Admin par default
app.admin.email=analyticsqhse@gmail.com
app.admin.password=aobg noqk ovmw mwar
app.admin.nom=Super
app.admin.prenom=Admin

# URL Frontend
app.frontend.url=${APP_FRONTEND_URL:http://localhost:4200}

# CORS
app.cors.allowed-origins=http://localhost:4200

# Groq
app.groq.api-key=aobg noqk ovmw mwar
app.groq.model=llama-3.1-8b-instant
app.groq.timeout=30

# Actuator - Health check pour Docker
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.server.port=8080